import logging
from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from feedly.models import (
    Organization, OrganizationMember, Recipient, SurplusFood, 
    Delivery, Redistribution, ProduceTraceabilityLedger, SystemEvent
)

User = get_user_model()
logger = logging.getLogger(__name__)

class Command(BaseCommand):
    help = 'Clears data generated by seed_demo_data to prepare for a fresh SIH demo run.'

    def handle(self, *args, **kwargs):
        self.stdout.write("Starting demo data clearance...")

        try:
            # 1. Identify the demo user and organization
            user = User.objects.filter(username="sih_admin").first()
            if not user:
                self.stdout.write(self.style.WARNING("sih_admin user not found. Demo data may not exist."))
                return

            org = Organization.objects.filter(name="SIH Operations HQ").first()
            
            if org:
                self.stdout.write(f"Clearing records for organization: {org.name}")
                # Django's CASCADE deletion on Organization will handle most related entities,
                # but we'll explicitly clear them to be safe and clear log-type models.
                
                ProduceTraceabilityLedger.objects.filter(organization=org).delete()
                SystemEvent.objects.filter(organization=org).delete()
                Delivery.objects.filter(sender=org).delete()
                Redistribution.objects.filter(organization=org).delete()
                SurplusFood.objects.filter(organization=org).delete()
                Recipient.objects.filter(organization=org).delete()
                OrganizationMember.objects.filter(organization=org).delete()
                
                # Finally delete the organization itself
                org.delete()
                self.stdout.write("Deleted SIH Operations HQ organization and related records.")

            # Delete the demo user
            user.delete()
            self.stdout.write("Deleted sih_admin user.")

            self.stdout.write(self.style.SUCCESS("Successfully cleared SIH demo data!"))

        except Exception as e:
            self.stdout.write(self.style.ERROR(f"Error clearing demo data: {e}"))
            logger.exception(e)
