# Generated by Django 6.0.8 on 2026-08-20 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="delivery",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="mealrecord",
            name="rainfall",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="distance_km",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="urgency_score",
            field=models.PositiveIntegerField(
                default=50, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="redistribution",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="surplusfood",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="surplusfood",
            name="storage_time_hours",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
