# Generated by Django 5.2.17 on 2026-09-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0003_iottemperaturereading"),
    ]

    operations = [
        migrations.AddField(
            model_name="surplusfood",
            name="safety_alert",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="demandforecast",
            name="model_name",
            field=models.CharField(default="AgroFedlyFallback", max_length=100),
        ),
        migrations.AlterField(
            model_name="surplusfood",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SAFE", "Safe"),
                    ("WARNING", "Warning"),
                    ("UNSAFE", "Unsafe"),
                    ("REDISTRIBUTED", "Redistributed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
