# Generated by Django 5.2.17 on 2026-09-03 19:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0004_surplusfood_safety_alert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActualConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ingredient_name", models.CharField(max_length=150)),
                (
                    "consumed_quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("unit", models.CharField(default="kg", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_meals_planned", models.PositiveIntegerField(default=0)),
                ("total_waste", models.FloatField(default=0.0)),
                ("accuracy_score", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user_comments", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("issues_reported", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProduceRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient_name", models.CharField(max_length=150)),
                (
                    "required_quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("unit", models.CharField(default="kg", max_length=50)),
                (
                    "demand_forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produce_requirements",
                        to="feedly.demandforecast",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcurementGuidance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_cost",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("recommended_purchase_date", models.DateField(blank=True, null=True)),
                (
                    "produce_requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_guidance",
                        to="feedly.producerequirement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Waste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waste_quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("waste_reason", models.CharField(blank=True, max_length=200)),
                (
                    "cost_loss",
                    models.FloatField(
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "actual_consumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wastes",
                        to="feedly.actualconsumption",
                    ),
                ),
            ],
        ),
    ]
