# Generated by Django 5.2.17 on 2026-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0005_actualconsumption_analyticsreport_feedback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("unit", models.CharField(default="kg", max_length=20)),
                (
                    "quantity_per_meal",
                    models.FloatField(help_text="Quantity required per meal"),
                ),
                ("cost_per_unit", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="waste",
            name="actual_consumption",
        ),
        migrations.DeleteModel(
            name="AnalyticsReport",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.RemoveField(
            model_name="procurementguidance",
            name="produce_requirement",
        ),
        migrations.RemoveField(
            model_name="producerequirement",
            name="demand_forecast",
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="discarded_meals",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="leftover_meals",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="predicted_demand",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name="ActualConsumption",
        ),
        migrations.DeleteModel(
            name="Waste",
        ),
        migrations.DeleteModel(
            name="ProcurementGuidance",
        ),
        migrations.DeleteModel(
            name="ProduceRequirement",
        ),
    ]
