# Generated by Django 5.2.17 on 2026-09-03 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0006_ingredient_remove_waste_actual_consumption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandforecast",
            name="model_name",
            field=models.CharField(default="FedlyFallback", max_length=100),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("COMPANY", "Company"),
                    ("COLLEGE", "College"),
                    ("SCHOOL", "School"),
                    ("HOSPITAL", "Hospital"),
                    ("NGO", "NGO / Non-Profit"),
                    ("INSTITUTION", "Other Institution"),
                    ("SUPPLIER", "Agricultural Supplier / Farmer"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AgriculturalProduce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("category", models.CharField(max_length=100)),
                ("crop_type", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("unit", models.CharField(default="kg", max_length=20)),
                (
                    "available_quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("harvest_date", models.DateField()),
                ("expected_shelf_life_days", models.PositiveIntegerField(default=7)),
                (
                    "storage_condition",
                    models.CharField(default="Room Temperature", max_length=100),
                ),
                ("quality_status", models.CharField(default="Good", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produce_inventory",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgriculturalSupplyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("PROCESSING", "Processing"),
                            ("SUPPLIED", "Supplied"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "produce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_requests",
                        to="feedly.agriculturalproduce",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_requests",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)]
                    ),
                ),
                ("processing_type", models.CharField(max_length=150)),
                ("output_product", models.CharField(max_length=150)),
                (
                    "output_quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("processing_date", models.DateField(auto_now_add=True)),
                ("processing_facility", models.CharField(blank=True, max_length=150)),
                ("status", models.CharField(default="Completed", max_length=50)),
                ("waste_quantity", models.FloatField(default=0)),
                (
                    "input_produce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_records",
                        to="feedly.agriculturalproduce",
                    ),
                ),
            ],
        ),
    ]
