# Generated by Django 5.2.17 on 2026-09-12 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedly",
            "0009_cropmarkettrend_weatheradvisory_agriculturalshipment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgertransaction",
            name="escrow_status",
            field=models.CharField(
                choices=[
                    ("NONE", "No Escrow"),
                    ("HELD", "Held in Escrow"),
                    ("RELEASED", "Released"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CropDiseaseScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="disease_scans/"
                    ),
                ),
                (
                    "detected_disease",
                    models.CharField(default="Healthy", max_length=150),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("recommended_treatment", models.TextField(blank=True)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
