# Generated by Django 5.2.17 on 2026-09-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedly",
            "0011_governmentscheme_equipment_equipmentrental_farmfield_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumpost",
            name="author",
        ),
        migrations.AddField(
            model_name="delivery",
            name="current_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="current_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="proof_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="delivery_proofs/"
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="recipient_signature",
            field=models.TextField(
                blank=True, help_text="Base64 encoded signature image data"
            ),
        ),
        migrations.AlterField(
            model_name="agriculturalshipment",
            name="current_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agriculturalshipment",
            name="status",
            field=models.CharField(default="IN_TRANSIT", max_length=20),
        ),
        migrations.AlterField(
            model_name="agriculturalshipment",
            name="tracking_code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="cropdiseasescan",
            name="confidence",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="cropdiseasescan",
            name="detected_disease",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="cropdiseasescan",
            name="recommended_treatment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cropmarkettrend",
            name="price_per_kg",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="cropmarkettrend",
            name="record_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cropmarkettrend",
            name="region",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="equipment/"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="equipmentrental",
            name="status",
            field=models.CharField(default="REQUESTED", max_length=20),
        ),
        migrations.AlterField(
            model_name="farmfield",
            name="area_acres",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="farmfield",
            name="geojson_data",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="eligible_crops",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="ledgertransaction",
            name="escrow_status",
            field=models.CharField(default="RELEASED", max_length=20),
        ),
        migrations.AlterField(
            model_name="ledgertransaction",
            name="receiver_org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_transactions",
                to="feedly.organization",
            ),
        ),
        migrations.AlterField(
            model_name="ledgertransaction",
            name="reference_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="ledgertransaction",
            name="sender_org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_transactions",
                to="feedly.organization",
            ),
        ),
        migrations.AlterField(
            model_name="ledgertransaction",
            name="status",
            field=models.CharField(default="COMPLETED", max_length=20),
        ),
        migrations.AlterField(
            model_name="qualityinspection",
            name="grade",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="weatheradvisory",
            name="severity",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="CropYieldPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=100)),
                ("area_hectares", models.DecimalField(decimal_places=2, max_digits=10)),
                ("soil_type", models.CharField(max_length=100)),
                (
                    "predicted_yield_tons",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estimated_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ForumComment",
        ),
        migrations.DeleteModel(
            name="ForumPost",
        ),
    ]
