# Generated by Django 5.2.17 on 2026-09-13 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0012_remove_forumpost_author_delivery_current_lat_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_meals_saved", models.PositiveIntegerField(default=0)),
                ("total_co2_reduced_kg", models.FloatField(default=0.0)),
                ("impact_points", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impact",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "vehicle_type",
                    models.CharField(
                        blank=True, help_text="e.g., Bike, Car, Van", max_length=50
                    ),
                ),
                ("vehicle_number", models.CharField(blank=True, max_length=50)),
                ("is_available", models.BooleanField(default=True)),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="delivery",
            name="volunteer_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_deliveries",
                to="feedly.volunteerprofile",
            ),
        ),
    ]
