# Generated by Django 6.0.8 on 2026-09-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0013_organizationimpact_volunteerprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surplusfood",
            name="ai_freshness_score",
            field=models.IntegerField(
                blank=True, help_text="AI calculated freshness out of 100", null=True
            ),
        ),
        migrations.AddField(
            model_name="surplusfood",
            name="ai_quality_notes",
            field=models.TextField(blank=True, help_text="AI vision analysis notes"),
        ),
        migrations.AddField(
            model_name="surplusfood",
            name="quality_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="surplus_quality/"
            ),
        ),
    ]
