# Generated by Django 6.0.8 on 2026-09-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0015_foodledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "practice_type",
                    models.CharField(
                        help_text="e.g. Cover Crops, No-Till Farming, Methane Reduction",
                        max_length=100,
                    ),
                ),
                ("acres_applied", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "co2_sequestered_tons",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated CO2 offset",
                        max_digits=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("MINTED", "Minted/Verified"),
                            ("SOLD", "Sold"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "verification_hash",
                    models.CharField(
                        blank=True,
                        help_text="Cryptographic hash proving ledger entry",
                        max_length=64,
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_credits",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
    ]
