# Generated by Django 5.2.17 on 2026-09-14 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0016_carboncredit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPricePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                (
                    "current_price_per_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "predicted_price_next_week",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "predicted_price_month",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("confidence_score", models.IntegerField(help_text="0-100")),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("SELL_NOW", "Sell Now"),
                            ("HOLD", "Hold for Better Price"),
                            ("SELL_PARTIAL", "Sell Partial"),
                        ],
                        max_length=50,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CropInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                ("acres", models.DecimalField(decimal_places=2, max_digits=10)),
                ("premium_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payout_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "trigger_condition",
                    models.CharField(
                        help_text="e.g. 'Drought (< 10mm rain) or Flood'",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CLAIM_PENDING", "Claim Pending"),
                            ("PAID_OUT", "Paid Out"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CSABox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Ugly Veggies Weekly Box'", max_length=200
                    ),
                ),
                ("description", models.TextField()),
                ("price_per_box", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_subscriptions", models.IntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csa_boxes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CSASubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="feedly.csabox"
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_csa_subs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MicroLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual percentage rate",
                        max_digits=5,
                    ),
                ),
                ("purpose", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved & Disbursed"),
                            ("REPAID", "Fully Repaid"),
                            ("DEFAULTED", "Defaulted"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=255)),
                ("total_palettes", models.IntegerField()),
                ("available_palettes", models.IntegerField()),
                (
                    "price_per_palette_day",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "current_temp_celsius",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarehouseBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("palettes", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active / Stored"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedly.warehouse",
                    ),
                ),
            ],
        ),
    ]
