# Generated by Django 5.2.17 on 2026-09-14 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0018_droneimagery_freightlisting_freightbid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ESGReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_month",
                    models.CharField(help_text="e.g. October 2026", max_length=50),
                ),
                (
                    "total_food_rescued_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_meals_provided", models.IntegerField()),
                (
                    "carbon_emissions_saved_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esg_reports",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FleetRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=150)),
                ("vehicle_plate", models.CharField(max_length=50)),
                (
                    "optimized_path_json",
                    models.TextField(
                        help_text="JSON array of stops in optimized order"
                    ),
                ),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Dispatch"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_routes",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrantOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "provider",
                    models.CharField(
                        help_text="e.g. CSR Fund or Govt Body", max_length=200
                    ),
                ),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISCOVERED", "Discovered"),
                            ("PREPARING", "Preparing Application"),
                            ("APPLIED", "Applied"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                        ],
                        default="DISCOVERED",
                        max_length=50,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_grants",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="e.g. Warehouse Sorter, Driver", max_length=150
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("capacity", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="CONFIRMED",
                        max_length=50,
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="feedly.volunteershift",
                    ),
                ),
            ],
        ),
    ]
