# Generated by Django 5.2.17 on 2026-09-14 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0020_communityfridge_p2pfoodswap_usergreenscore"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("transaction_type", models.CharField(max_length=100)),
                ("sender", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=100)),
                ("amount_or_value", models.CharField(max_length=100)),
                ("cryptographic_hash", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DisasterZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Kerala Floods 2026", max_length=200
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Level 1: Critical"),
                            ("HIGH", "Level 2: High"),
                            ("STABILIZING", "Level 3: Stabilizing"),
                        ],
                        default="HIGH",
                        max_length=50,
                    ),
                ),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("required_meals", models.IntegerField(default=10000)),
                ("meals_fulfilled", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgriTourismListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("max_guests", models.IntegerField(default=2)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("FARM_STAY", "Overnight Farm Stay"),
                            ("TOUR", "Guided Farm Tour"),
                            ("WORKSHOP", "Farming Workshop"),
                        ],
                        default="FARM_STAY",
                        max_length=100,
                    ),
                ),
                ("image_url", models.CharField(blank=True, max_length=300)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tourism_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GreenhouseDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. LED Grow Light Array 1", max_length=100
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("LIGHT", "Grow Light"),
                            ("IRRIGATION", "Irrigation Pump"),
                            ("CLIMATE", "Climate Control (HVAC)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False, help_text="True = ON, False = OFF"
                    ),
                ),
                (
                    "reading",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 75% Humidity or 18 Hours/day",
                        max_length=50,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="greenhouse_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
