# Generated by Django 5.2.17 on 2026-09-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0023_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("ASSIGNED", "Driver Assigned"),
                    ("PICKED_UP", "Picked Up"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="REQUESTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mealrecord",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="surplusfood",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="surplusfood",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SAFE", "Safe"),
                    ("WARNING", "Warning"),
                    ("UNSAFE", "Unsafe"),
                    ("REDISTRIBUTED", "Redistributed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
