# Generated by Django 6.0.8 on 2026-09-15 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0025_rename_blockchainledger_producetraceabilityledger_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmfield",
            name="farmer",
        ),
        migrations.RemoveField(
            model_name="producetraceabilityledger",
            name="amount_or_value",
        ),
        migrations.RemoveField(
            model_name="producetraceabilityledger",
            name="cryptographic_hash",
        ),
        migrations.RemoveField(
            model_name="producetraceabilityledger",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="producetraceabilityledger",
            name="sender",
        ),
        migrations.AddField(
            model_name="agriculturalproduce",
            name="batch_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="agriculturalproduce",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produces",
                to="feedly.farmfield",
            ),
        ),
        migrations.AddField(
            model_name="agriculturalproduce",
            name="processing_status",
            field=models.CharField(default="RAW", max_length=50),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farms",
                to="feedly.organization",
            ),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="recommended_production",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="safety_buffer_percent",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="producetraceabilityledger",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="producetraceabilityledger",
            name="batch_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="producetraceabilityledger",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="producetraceabilityledger",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedly.organization",
            ),
        ),
        migrations.AddField(
            model_name="producetraceabilityledger",
            name="produce",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedly.agriculturalproduce",
            ),
        ),
        migrations.AddField(
            model_name="producetraceabilityledger",
            name="quantity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="producetraceabilityledger",
            name="surplus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedly.surplusfood",
            ),
        ),
        migrations.AlterField(
            model_name="farmfield",
            name="geojson_data",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="StorageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=150)),
                (
                    "quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("unit", models.CharField(default="kg", max_length=20)),
                ("entry_time", models.DateTimeField(auto_now_add=True)),
                ("temperature_celsius", models.FloatField(default=4.0)),
                ("humidity_percent", models.FloatField(default=60.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SAFE", "Safe - Optimal Conditions"),
                            ("MONITOR", "Monitor - Nearing Threshold"),
                            ("ATTENTION", "Attention Required - Deviation Detected"),
                            ("CRITICAL", "Critical - Spoilage Risk"),
                        ],
                        default="SAFE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_records",
                        to="feedly.organization",
                    ),
                ),
                (
                    "produce",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_records",
                        to="feedly.agriculturalproduce",
                    ),
                ),
                (
                    "surplus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_records",
                        to="feedly.surplusfood",
                    ),
                ),
            ],
        ),
    ]
