# Generated by Django 5.2.17 on 2026-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0026_remove_farmfield_farmer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agriculturalproduce",
            name="is_demo",
            field=models.BooleanField(default=False, help_text="SIH Demo Data Flag"),
        ),
        migrations.AddField(
            model_name="delivery",
            name="is_demo",
            field=models.BooleanField(default=False, help_text="SIH Demo Data Flag"),
        ),
        migrations.AddField(
            model_name="demandforecast",
            name="is_demo",
            field=models.BooleanField(default=False, help_text="SIH Demo Data Flag"),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="is_demo",
            field=models.BooleanField(default=False, help_text="SIH Demo Data Flag"),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_demo",
            field=models.BooleanField(default=False, help_text="SIH Demo Data Flag"),
        ),
        migrations.AddField(
            model_name="recipient",
            name="is_demo",
            field=models.BooleanField(default=False, help_text="SIH Demo Data Flag"),
        ),
        migrations.AddField(
            model_name="surplusfood",
            name="is_demo",
            field=models.BooleanField(default=False, help_text="SIH Demo Data Flag"),
        ),
    ]
