# Generated by Django 5.2.17 on 2026-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0028_airecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="airecommendation",
            name="is_demo",
            field=models.BooleanField(default=False, help_text="SIH Demo Data Flag"),
        ),
    ]
