# Generated by Django 5.2.17 on 2026-09-16 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0029_airecommendation_is_demo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("request_intent", models.CharField(max_length=250)),
                ("ai_module", models.CharField(max_length=100)),
                (
                    "model_version",
                    models.CharField(default="AgroFedly AI 1.0", max_length=100),
                ),
                (
                    "inputs_snapshot",
                    models.TextField(
                        blank=True, help_text="JSON representation of inputs"
                    ),
                ),
                ("recommendation", models.TextField()),
                ("confidence", models.CharField(blank=True, max_length=50)),
                ("action_requested", models.CharField(blank=True, max_length=200)),
                ("user_decision", models.CharField(blank=True, max_length=50)),
                ("execution_result", models.CharField(blank=True, max_length=50)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "is_demo",
                    models.BooleanField(default=False, help_text="SIH Demo Data Flag"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_audit_logs",
                        to="feedly.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
