# Generated by Django 5.2.17 on 2026-09-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0031_dataimport_systemevent_usertask_workflowrule_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agriculturalproduce",
            name="is_demo",
        ),
        migrations.RemoveField(
            model_name="aiauditlog",
            name="is_demo",
        ),
        migrations.RemoveField(
            model_name="airecommendation",
            name="is_demo",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="is_demo",
        ),
        migrations.RemoveField(
            model_name="demandforecast",
            name="is_demo",
        ),
        migrations.RemoveField(
            model_name="mealrecord",
            name="is_demo",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="is_demo",
        ),
        migrations.RemoveField(
            model_name="recipient",
            name="is_demo",
        ),
        migrations.RemoveField(
            model_name="surplusfood",
            name="is_demo",
        ),
    ]
