# Generated by Django 5.2.17 on 2026-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0032_remove_agriculturalproduce_is_demo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="onboarding_step",
            field=models.IntegerField(default=1),
        ),
    ]
