# Generated by Django 6.0.8 on 2026-09-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0036_apikey_tenantauditlog_webhook"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("FARMER", "Farmer"),
                            ("FPO", "Farmer Organization / FPO"),
                            ("OFFICER", "Agriculture Officer"),
                            ("AGRIBUSINESS", "Agribusiness"),
                            ("NGO", "NGO / Redistribution"),
                            ("RESEARCHER", "Researcher"),
                            ("ADMIN", "Administrator"),
                        ],
                        default="FARMER",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "organization_id",
                    models.CharField(
                        blank=True,
                        help_text="For FPO, Agribusiness, NGO",
                        max_length=100,
                    ),
                ),
                (
                    "official_id",
                    models.CharField(
                        blank=True, help_text="For Agriculture Officer", max_length=100
                    ),
                ),
                (
                    "researcher_id",
                    models.CharField(
                        blank=True, help_text="For Researchers", max_length=100
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
