# Generated by Django 6.0.8 on 2026-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0038_agriculturalproduce_owner_farmfield_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmfield",
            name="soil_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
