# Generated by Django 6.0.8 on 2026-09-17 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0040_buyerdemand_owner_alter_buyerdemand_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="farmfield",
            name="expected_harvest_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="health_status",
            field=models.CharField(default="Good", max_length=50),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="irrigation_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="planting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("area_acres", models.FloatField(default=0.0)),
                ("soil_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "irrigation_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ownership_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("geojson_boundary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms_list",
                        to="feedly.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_farms_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="farmfield",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="feedly.farm",
            ),
        ),
        migrations.CreateModel(
            name="FarmEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("event_type", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="feedly.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_type", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=150)),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(max_length=20)),
                ("low_stock_threshold", models.FloatField(default=0.0)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="feedly.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("quantity", models.CharField(blank=True, max_length=100)),
                (
                    "attachment",
                    models.ImageField(
                        blank=True, null=True, upload_to="field_activities/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="feedly.farmfield",
                    ),
                ),
            ],
        ),
    ]
