# Generated by Django 6.0.8 on 2026-09-17 15:49

from django.db import migrations


def migrate_farm_fields(apps, schema_editor):
    Farm = apps.get_model('feedly', 'Farm')
    FarmField = apps.get_model('feedly', 'FarmField')
    
    for field in FarmField.objects.all():
        # Create a Farm based on the FarmField's attributes
        farm = Farm.objects.create(
            organization=field.organization,
            owner=field.owner,
            name=field.name + " Farm",  # To distinguish the farm from the field
            area_acres=field.area_acres,
            soil_type=field.soil_type,
            geojson_boundary=field.geojson_data
        )
        
        # Link the Field to the new Farm
        field.farm = farm
        field.save()

class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0041_farmfield_expected_harvest_date_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_farm_fields),
    ]
