# Generated by Django 5.2.17 on 2026-09-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0043_aimodelregistry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealrecord",
            name="event_mode",
            field=models.CharField(default="Normal", max_length=100),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="expected_attendance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="meal_session",
            field=models.CharField(default="Lunch", max_length=50),
        ),
        migrations.AddField(
            model_name="surplusfood",
            name="measured_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surplusfood",
            name="safety_status",
            field=models.CharField(default="PENDING_CHECK", max_length=50),
        ),
        migrations.CreateModel(
            name="Kitchen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("kitchen_type", models.CharField(default="Hostel", max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("operating_hours", models.CharField(blank=True, max_length=100)),
                ("daily_meal_capacity", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchens",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="kitchen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_records",
                to="feedly.kitchen",
            ),
        ),
        migrations.AddField(
            model_name="surplusfood",
            name="kitchen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surplus_records",
                to="feedly.kitchen",
            ),
        ),
        migrations.CreateModel(
            name="KitchenAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("severity", models.CharField(default="INFO", max_length=30)),
                ("reason", models.CharField(max_length=255)),
                ("source", models.CharField(default="SYSTEM", max_length=100)),
                ("action_required", models.CharField(blank=True, max_length=255)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kitchen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="feedly.kitchen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KitchenInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient", models.CharField(max_length=150)),
                ("quantity", models.FloatField(default=0.0)),
                ("unit", models.CharField(default="kg", max_length=20)),
                ("batch_id", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField(auto_now_add=True)),
                ("expiry_date", models.DateField()),
                ("storage_location", models.CharField(blank=True, max_length=100)),
                ("supplier", models.CharField(blank=True, max_length=150)),
                ("status", models.CharField(default="ACTIVE", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kitchen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="feedly.kitchen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreparationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_item", models.CharField(max_length=150)),
                ("planned_qty", models.FloatField(default=0.0)),
                ("prepared_qty", models.FloatField(default=0.0)),
                ("served_qty", models.FloatField(default=0.0)),
                ("unit", models.CharField(default="kg", max_length=20)),
                ("preparation_time", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kitchen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparations",
                        to="feedly.kitchen",
                    ),
                ),
                (
                    "meal_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparations",
                        to="feedly.mealrecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="surplusfood",
            name="preparation_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surplus_records",
                to="feedly.preparationrecord",
            ),
        ),
    ]
