# Generated by Django 5.2.17 on 2026-09-18 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedly",
            "0044_mealrecord_event_mode_mealrecord_expected_attendance_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="airecommendation",
            name="confidence",
            field=models.FloatField(
                blank=True, help_text="AI Confidence 0.0 to 100.0", null=True
            ),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="explanation",
            field=models.TextField(
                blank=True, help_text="Detailed WHY for the recommendation"
            ),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="requires_human_approval",
            field=models.BooleanField(
                default=True, help_text="If true, cannot be auto-executed"
            ),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("APPROACHING", "Approaching"),
                    ("READY", "Ready"),
                    ("HARVESTED", "Harvested"),
                    ("DELAYED", "Delayed"),
                    ("PARTIAL", "Partial"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AppError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("error_type", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("traceback", models.TextField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low (Warning)"),
                            ("MEDIUM", "Medium (Recoverable Error)"),
                            ("HIGH", "High (Critical Failure)"),
                        ],
                        default="MEDIUM",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="NEW",
                        max_length=15,
                    ),
                ),
                ("occurrence_count", models.IntegerField(default=1)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="feedly.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
