# Generated by Django 5.2.17 on 2026-09-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0046_integrationconfig_iotdevice_iotalertthreshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agriculturalproduce",
            name="marketplace_status",
            field=models.CharField(
                choices=[
                    ("NOT_LISTED", "Not Listed"),
                    ("LISTED", "Listed"),
                    ("PENDING_QUALITY_CHECK", "Pending Quality Check"),
                    ("BOOKED", "Booked"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                ],
                default="NOT_LISTED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="agriculturalproduce",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="last_maintenance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="maintenance_status",
            field=models.CharField(
                choices=[
                    ("OK", "OK"),
                    ("MAINTENANCE_DUE", "Maintenance Due"),
                    ("OVERDUE", "Overdue"),
                    ("REPORTED_ISSUE", "Reported Issue"),
                ],
                default="OK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="next_maintenance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="operating_hours",
            field=models.IntegerField(default=0),
        ),
    ]
