# Generated by Django 5.2.17 on 2026-09-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0048_agriculturalproduce_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="data_retention_days",
            field=models.PositiveIntegerField(
                default=365, help_text="Number of days to keep archived data"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_organizations",
                to="feedly.organization",
            ),
        ),
    ]
