# Generated by Django 5.2.17 on 2026-09-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0049_organization_data_retention_days_organization_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("INGREDIENTS_READY", "Ingredients Ready"),
                    ("PREPARING", "Preparing"),
                    ("READY", "Ready"),
                    ("SERVING", "Serving"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PLANNED",
                max_length=30,
            ),
        ),
    ]
