# Generated by Django 5.2.17 on 2026-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0050_mealrecord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INVITED", "Invited"),
                    ("PENDING", "Pending Setup"),
                    ("SUSPENDED", "Suspended"),
                    ("DISABLED", "Disabled"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_step",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_workspace",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
    ]
