# Generated by Django 5.2.17 on 2026-09-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0051_userprofile_account_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("FARMER", "Farmer"),
                    ("FPO", "Farmer Organization / FPO"),
                    ("OFFICER", "Agriculture Officer"),
                    ("AGRIBUSINESS", "Agribusiness"),
                    ("NGO", "NGO / Redistribution"),
                    ("RESEARCHER", "Researcher"),
                    ("ADMIN", "Administrator"),
                    ("SUPER_ADMIN", "Super Admin"),
                ],
                default="FARMER",
                max_length=20,
            ),
        ),
    ]
