# Generated by Django 5.2.17 on 2026-09-20 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0052_alter_userprofile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("license_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("On Route", "On Route"),
                            ("Resting", "Resting"),
                        ],
                        default="Available",
                        max_length=50,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("joined_date", models.DateField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logistics_drivers",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
    ]
