# Generated by Django 5.2.17 on 2026-09-20 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0053_logisticsdriver"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="logistics_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="feedly.logisticsdriver",
            ),
        ),
    ]
