# Generated by Django 5.2.17 on 2026-09-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0054_delivery_logistics_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationmember",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Assignment"),
                    ("FARMER", "Farmer"),
                    ("FPO", "Farmer Organization / FPO"),
                    ("OFFICER", "Agriculture Officer"),
                    ("AGRIBUSINESS", "Agribusiness"),
                    ("NGO", "NGO / Redistribution"),
                    ("RESEARCHER", "Researcher"),
                    ("ADMIN", "Administrator"),
                    ("SUPER_ADMIN", "Super Admin"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
