# Generated by Django 5.2.17 on 2026-09-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0055_remove_organizationmember_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmfield",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                ("forecast_time", models.TimeField(blank=True, null=True)),
                ("temperature_min", models.FloatField()),
                ("temperature_max", models.FloatField()),
                ("rain_probability", models.FloatField(blank=True, null=True)),
                ("precipitation", models.FloatField(default=0.0)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                ("condition", models.CharField(max_length=100)),
                ("source", models.CharField(default="OpenWeather", max_length=100)),
                ("retrieved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_forecasts",
                        to="feedly.farm",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_forecasts",
                        to="feedly.farmfield",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("observed_at", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.FloatField()),
                ("feels_like", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField()),
                ("pressure", models.FloatField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                ("wind_direction", models.FloatField(blank=True, null=True)),
                ("cloud_cover", models.FloatField(blank=True, null=True)),
                ("precipitation", models.FloatField(default=0.0)),
                ("rain_probability", models.FloatField(blank=True, null=True)),
                ("uv_index", models.FloatField(blank=True, null=True)),
                ("visibility", models.FloatField(blank=True, null=True)),
                ("condition", models.CharField(max_length=100)),
                ("source", models.CharField(default="OpenWeather", max_length=100)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_observations",
                        to="feedly.farm",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_observations",
                        to="feedly.farmfield",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_observations",
                        to="feedly.organization",
                    ),
                ),
            ],
        ),
    ]
