# Generated by Django 5.2.17 on 2026-09-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedly", "0056_farm_latitude_farm_longitude_farmfield_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agriculturalproduce",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
